### ISSUE TITLE
'counsel-fd-dired-jump should enter selected directory?

### ISSUE THREAD

**Issue by articuluxe** [yqrashawn/counsel-fd#1]
Thank you for your library.

I would expect (and find more useful) if 'counsel-fd-dired-jump would actually enter the directory I selected, rather than putting the cursor on the directory from its parent.  If I select it, I want to enter it.

What do you think?

**Comment by yqrashawn** [comment]
Hi, it seems you post the issue to the wrong repo. [This](https://github.com/jethrokuan/counsel-fd) is the right one.
